---
- hosts: localhost
  name: Setup database
  become: no
  tasks:
    - postgresql_db:
        name: bc-wallet-tron-hdwallet
        encoding: UTF-8
        login_host: data.tr.gdrn.me
        login_password: password
        login_user: postgres
        port: 5434

    - postgresql_schema:
        db: bc-wallet-tron-hdwallet
        name: public
        login_host: data.tr.gdrn.me
        login_password: password
        login_user: postgres
        port: 5434

    - postgresql_user:
        db: bc-wallet-tron-hdwallet
        name: bc-wallet-tron-hdwallet-api
        password: password
        expires: infinity
        login_host: data.tr.gdrn.me
        login_password: password
        login_user: postgres
        port: 5434

    -  postgresql_privs:
        state: present
        db: bc-wallet-tron-hdwallet
        privs: CONNECT
        grant_option: false
        type: database
        roles: bc-wallet-tron-hdwallet-api
        login_host: data.tr.gdrn.me
        login_password: password
        login_user: postgres
        port: 5434

    -  postgresql_privs:
         state: present
         db: bc-wallet-tron-hdwallet
         privs: SELECT,INSERT,UPDATE,DELETE
         grant_option: false
         type: table
         objs: ALL_IN_SCHEMA
         roles: bc-wallet-tron-hdwallet-api
         login_host: data.tr.gdrn.me
         login_password: password
         login_user: postgres
         port: 5434

    - postgresql_user:
        db: bc-wallet-tron-hdwallet
        name: bc-wallet-tron-hdwallet-migrator
        password: password
        expires: infinity
        login_host: data.tr.gdrn.me
        login_password: password
        login_user: postgres
        port: 5434

    - postgresql_privs:
        state: present
        db: bc-wallet-tron-hdwallet
        privs: ALL
        grant_option: false
        objs: public
        type: schema
        roles: bc-wallet-tron-hdwallet-migrator
        login_host: data.tr.gdrn.me
        login_password: password
        login_user: postgres
        port: 5434